config/routes.rb
Rails.application.routes.draw do
  root  to: 'home#index'

  resources :movies, only: [:show, :new, :create, :edit, :update] do
    patch :publish, on: :member
  end
  resources :movie_genres, only: [:show, :new, :create, :edit, :update]
  resources :directors, only: [:show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  enum status: {draft:0, published: 2}

  belongs_to :director
  belongs_to :movie_genre
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
    has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def show
    @director = Director.find(params[:id])
    @movies = @director.movies
    flash[:notice] = 'Diretor cadastrado com sucesso!' if params[:created].present?
    flash[:notice] = 'Diretor editado com sucesso!' if params[:updated].present?
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new(name: params[:director][:name],
                            origin_country: params[:director][:origin_country],
                            birth_date: params[:director][:birth_date],
                            favorite_genre: params[:director][:favorite_genre])
    if @director.save
      return redirect_to director_path(@director.id, created: true)
    end

    render :new
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    if @director.update(name: params[:director][:name],
                        origin_country: params[:director][:origin_country],
                        birth_date: params[:director][:birth_date],
                        favorite_genre: params[:director][:favorite_genre])
     return redirect_to director_path(@director.id, updated: true)
    end

    render :edit
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.published
    @movie_genres = MovieGenre.all
    @director = Director.all
  end
end

app/controllers/movie_genres_controller.rb
class MovieGenresController < ApplicationController
  def show
    @movie_genre = MovieGenre.find(params[:id])
    @movies = @movie_genre.movies
    flash[:notice] = 'Gênero cadastrado com sucesso!' if params[:created].present?
    flash[:notice] = 'Gênero editado com sucesso!' if params[:updated].present?
  end

  def new
    @movie_genre = MovieGenre.new
  end

  def create
    @movie_genre = MovieGenre.new(name: params[:movie_genre][:name])
    if @movie_genre.save
      return redirect_to movie_genre_path(@movie_genre.id, created: true)
    end

    render :new
  end

  def edit
    @movie_genre = MovieGenre.find(params[:id])    
  end

  def update
    @movie_genre = MovieGenre.find(params[:id])
    if @movie_genre.update(name: params[:movie_genre][:name])
      return redirect_to movie_genre_path(@movie_genre.id, updated: true)
    end

    render :edit
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
    @movie = Movie.find(params[:id])
    flash[:notice] = 'Filme cadastrado com sucesso!' if params[:created].present?
    flash[:notice] = 'Filme editado com sucesso!' if params[:updated].present?
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(title: params[:movie][:title],
                      release_year: params[:movie][:release_year],
                      sinopsis: params[:movie][:sinopsis],
                      origin_country: params[:movie][:origin_country],
                      duration: params[:movie][:duration],
                      director_id: params[:movie][:director_id],
                      movie_genre_id: params[:movie][:movie_genre_id])
    if @movie.save
      return redirect_to movie_path(@movie.id, created: true)
    end

    render :new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(title: params[:movie][:title],
                  release_year: params[:movie][:release_year],
                  sinopsis: params[:movie][:sinopsis],
                  origin_country: params[:movie][:origin_country],
                  duration: params[:movie][:duration],
                  director_id: params[:movie][:director_id],
                  movie_genre_id: params[:movie][:movie_genre_id])
      return redirect_to movie_path(@movie.id, updated: true)
    end

    render :edit
  end

  def publish
    @movie = Movie.find(params[:id])
    @movie.published!
    redirect_to movie_path(@movie.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/_form.html.erb
<%= form_with model:director do |f|%>
<div>
<%= f.label 'Nome' %>
<%= f.text_field :name %>
</div>

<div>
<%= f.label 'País de Origem' %>
<%= f.text_field :origin_country %>
</div>

<div>
<%= f.label 'Ano de Nascimento' %>
<%= f.date_field :birth_date %>
</div>

<div>
<%= f.label 'Gênero Favorito' %>
<%= f.text_field :favorite_genre %>
</div>

<div style="margin-top: 10px">
<%= f.submit 'Salvar' %>
</div>

<% end %>

app/views/directors/edit.html.erb
<h3> Editar Diretor </h3>
<%= render partial: 'form', locals: {director: @director}%>

app/views/directors/new.html.erb
<h3> Cadastrar novo Diretor </h3>
<%= render partial: 'form', locals: {director: @director}%>

app/views/directors/show.html.erb
<h3> Diretor </h3>
<div>Nome: <%= @director.name %></div>
<div>País de Origem: <%= @director.origin_country %></div>
<div>Ano de Nascimento: <%= @director.birth_date %></div>
<div>Gênero Favorito: <%= @director.favorite_genre %></div>
<%= link_to 'Editar', edit_director_path(@director.id)%>

<% if flash[:notice].present? %>
<div>
<%= flash[:notice] %>
</div>
<% end %>

<h4>Filmes cadastrados que tem como diretor: <%= @director.name %> </h4>
<ul>
<% @movies.each do |movie| %>
<li><%= movie.title %> </li>
<% end %>
</ul>

app/views/home/index.html.erb
<h3> Filmes Cadastrados </h3>
<% @movies.each do |movie| %>
<%= link_to "#{movie.title}-#{movie.release_year}", movie_path(movie.id), style: "margin-right: 15px" %>
<% end %>
<h4><%= link_to 'Cadastrar novo filme', new_movie_path %></h4>

<h3> Gêneros Cadastrados </h3>
<% @movie_genres.each do |movie_genre| %>
<%= link_to movie_genre.name, movie_genre_path(movie_genre.id), style: "margin-right: 15px" %>
<% end %>
<h4><%= link_to 'Cadastrar novo gênero', new_movie_genre_path %></h4>

<h3> Diretores Cadastrados </h3>
<% @director.each do |director| %>
<%= link_to director.name, director_path(director.id), style: "margin-right: 15px" %>
<% end %>
<h4><%= link_to 'Cadastrar novo diretor', new_director_path %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to 'Página Inicial', root_path %>
    <%= yield %>
  </body>
</html>

app/views/movie_genres/_form.html.erb
<%= form_with model:movie_genre do |f|%>
<div>
<%= f.label 'Nome' %>
<%= f.text_field :name %>
</div>

<div style="margin-top: 10px">
<%= f.submit 'Salvar' %>
</div>

<% end %>

app/views/movie_genres/edit.html.erb
<h3> Editar Gênero </h3>
<%= render partial: 'form', locals: {movie_genre: @movie_genre}%>

app/views/movie_genres/new.html.erb
<h3> Cadastrar novo Gênero </h3>
<%= render partial: 'form', locals: {movie_genre: @movie_genre}%>

app/views/movie_genres/show.html.erb
<h3> Gênero </h3>
<div>Nome: <%= @movie_genre.name %></div>
<%= link_to 'Editar', edit_movie_genre_path(@movie_genre.id)%>

<% if flash[:notice].present? %>
<div>
<%= flash[:notice] %>
</div>
<% end %>

<h4>Filmes cadastrados com gênero: <%= @movie_genre.name %></h4>
<ul>
<% @movies.each do |movie|%>
<li><%= movie.title%></li>
<% end %>
</ul>

app/views/movies/_form.html.erb
<%= form_with model:movie do |f|%>
<div>
<%= f.label 'Título' %>
<%= f.text_field :title %>
</div>

<div>
<%= f.label 'Ano de Lançamento' %>
<%= f.number_field :release_year %>
</div>

<div>
<%= f.label 'Sinopse' %>
<%= f.text_field :sinopsis %>
</div>

<div>
<%= f.label 'País de Origem' %>
<%= f.text_field :origin_country %>
</div>

<div>
<%= f.label 'Duração' %>
<%= f.number_field :duration %>
</div>

<div>
<%= f.label 'Diretor' %>
<%= f.collection_select :director_id, Director.all, :id, :name %>
</div>

<div>
<%= f.label 'Gênero' %>
<%= f.collection_select :movie_genre_id, MovieGenre.all, :id, :name %>
</div>

<div style="margin-top: 10px">
<%= f.submit 'Salvar' %>
</div>

<% end %>

app/views/movies/edit.html.erb
<h3> Editar Filme </h3>
<%= render partial: 'form', locals: {movie: @movie} %>

app/views/movies/new.html.erb
<h3> Cadastrar novo Filme </h3>
<%= render partial: 'form', locals: {movie: @movie} %>

app/views/movies/show.html.erb
<h3> Filme </h3>
<div>Nome: <%= @movie.title %></div>
<div>Ano de Lançamento: <%= @movie.release_year %></div>
<div>Sinopse: <%= @movie.sinopsis %></div>
<div>País de Origem: <%= @movie.origin_country %></div>
<div>Duração: <%= @movie.duration %></div>
<div>Diretor: <%= @movie.director.name %></div>
<div>Gênero: <%= @movie.movie_genre.name %></div>
<div>Status: <%= @movie.status %></div>

<%= link_to 'Editar', edit_movie_path(@movie.id)%>

<% if flash[:notice].present? %>
<div>
<%= flash[:notice] %>
</div>
<% end %>

<%= button_to 'Publicar', publish_movie_path, {method: 'patch'} %>